{ "category" : { "description" : "",
      "id" : 6,
      "parent" : 4,
      "post_count" : 23,
      "slug" : "november-17th",
      "title" : "November 17th"
    },
  "count" : 10,
  "pages" : 3,
  "posts" : [ { "attachments" : [  ],
        "author" : { "description" : "",
            "first_name" : "",
            "id" : 1,
            "last_name" : "",
            "name" : "Napaba",
            "nickname" : "Napaba",
            "slug" : "napaba",
            "url" : ""
          },
        "categories" : [ { "description" : "",
              "id" : 6,
              "parent" : 4,
              "post_count" : 23,
              "slug" : "november-17th",
              "title" : "November 17th"
            },
            { "description" : "",
              "id" : 4,
              "parent" : 0,
              "post_count" : 114,
              "slug" : "program-schedule",
              "title" : "Program Schedule"
            }
          ],
        "comment_count" : 0,
        "comment_status" : "open",
        "comments" : [  ],
        "content" : "",
        "custom_fields" : { "event_time" : [ "10:00PM-2:00AM" ] },
        "date" : "2011-08-23 21:39:06",
        "excerpt" : "",
        "id" : 194,
        "modified" : "2011-08-23 21:39:06",
        "slug" : "late-night-lounge-series",
        "status" : "publish",
        "tags" : [  ],
        "title" : "Late Night Lounge Series",
        "title_plain" : "Late Night Lounge Series",
        "type" : "post",
        "url" : "http://convention.napaba.org/2011/08/late-night-lounge-series/"
      },
      { "attachments" : [  ],
        "author" : { "description" : "",
            "first_name" : "",
            "id" : 1,
            "last_name" : "",
            "name" : "Napaba",
            "nickname" : "Napaba",
            "slug" : "napaba",
            "url" : ""
          },
        "categories" : [ { "description" : "",
              "id" : 6,
              "parent" : 4,
              "post_count" : 23,
              "slug" : "november-17th",
              "title" : "November 17th"
            },
            { "description" : "",
              "id" : 4,
              "parent" : 0,
              "post_count" : 114,
              "slug" : "program-schedule",
              "title" : "Program Schedule"
            }
          ],
        "comment_count" : 0,
        "comment_status" : "open",
        "comments" : [  ],
        "content" : "",
        "custom_fields" : { "event_time" : [ "8:00PM-10:00PM" ] },
        "date" : "2011-08-23 21:37:53",
        "excerpt" : "",
        "id" : 192,
        "modified" : "2011-08-23 21:37:53",
        "slug" : "leadership-advisory-council-dinner",
        "status" : "publish",
        "tags" : [  ],
        "title" : "Leadership Advisory Council Dinner",
        "title_plain" : "Leadership Advisory Council Dinner",
        "type" : "post",
        "url" : "http://convention.napaba.org/2011/08/leadership-advisory-council-dinner/"
      },
      { "attachments" : [  ],
        "author" : { "description" : "",
            "first_name" : "",
            "id" : 1,
            "last_name" : "",
            "name" : "Napaba",
            "nickname" : "Napaba",
            "slug" : "napaba",
            "url" : ""
          },
        "categories" : [ { "description" : "",
              "id" : 6,
              "parent" : 4,
              "post_count" : 23,
              "slug" : "november-17th",
              "title" : "November 17th"
            },
            { "description" : "",
              "id" : 4,
              "parent" : 0,
              "post_count" : 114,
              "slug" : "program-schedule",
              "title" : "Program Schedule"
            }
          ],
        "comment_count" : 0,
        "comment_status" : "open",
        "comments" : [  ],
        "content" : "",
        "custom_fields" : { "event_time" : [ "8:00PM-10:00PM" ] },
        "date" : "2011-08-23 21:37:34",
        "excerpt" : "",
        "id" : 190,
        "modified" : "2011-08-23 21:37:34",
        "slug" : "young-lawyersblifirst-time-attendees-dinner-advance-registration-required",
        "status" : "publish",
        "tags" : [  ],
        "title" : "Young Lawyers/BLI/First Time Attendees Dinner (advance registration required)",
        "title_plain" : "Young Lawyers/BLI/First Time Attendees Dinner (advance registration required)",
        "type" : "post",
        "url" : "http://convention.napaba.org/2011/08/young-lawyersblifirst-time-attendees-dinner-advance-registration-required/"
      },
      { "attachments" : [  ],
        "author" : { "description" : "",
            "first_name" : "",
            "id" : 1,
            "last_name" : "",
            "name" : "Napaba",
            "nickname" : "Napaba",
            "slug" : "napaba",
            "url" : ""
          },
        "categories" : [ { "description" : "",
              "id" : 6,
              "parent" : 4,
              "post_count" : 23,
              "slug" : "november-17th",
              "title" : "November 17th"
            },
            { "description" : "",
              "id" : 4,
              "parent" : 0,
              "post_count" : 114,
              "slug" : "program-schedule",
              "title" : "Program Schedule"
            }
          ],
        "comment_count" : 0,
        "comment_status" : "open",
        "comments" : [  ],
        "content" : "",
        "custom_fields" : { "event_time" : [ "5:00PM-6:00PM" ] },
        "date" : "2011-08-23 21:37:09",
        "excerpt" : "",
        "id" : 188,
        "modified" : "2011-08-23 21:37:09",
        "slug" : "international-law-symposium-reception",
        "status" : "publish",
        "tags" : [  ],
        "title" : "International Law Symposium Reception",
        "title_plain" : "International Law Symposium Reception",
        "type" : "post",
        "url" : "http://convention.napaba.org/2011/08/international-law-symposium-reception/"
      },
      { "attachments" : [  ],
        "author" : { "description" : "",
            "first_name" : "",
            "id" : 1,
            "last_name" : "",
            "name" : "Napaba",
            "nickname" : "Napaba",
            "slug" : "napaba",
            "url" : ""
          },
        "categories" : [ { "description" : "",
              "id" : 6,
              "parent" : 4,
              "post_count" : 23,
              "slug" : "november-17th",
              "title" : "November 17th"
            },
            { "description" : "",
              "id" : 4,
              "parent" : 0,
              "post_count" : 114,
              "slug" : "program-schedule",
              "title" : "Program Schedule"
            }
          ],
        "comment_count" : 0,
        "comment_status" : "open",
        "comments" : [  ],
        "content" : "",
        "custom_fields" : { "event_time" : [ "8:00PM-10:00PM" ] },
        "date" : "2011-08-23 21:15:46",
        "excerpt" : "",
        "id" : 186,
        "modified" : "2011-08-23 21:15:46",
        "slug" : "international-law-symposium-dinner-advance-registration-required",
        "status" : "publish",
        "tags" : [  ],
        "title" : "International Law Symposium Dinner (advance registration required)",
        "title_plain" : "International Law Symposium Dinner (advance registration required)",
        "type" : "post",
        "url" : "http://convention.napaba.org/2011/08/international-law-symposium-dinner-advance-registration-required/"
      },
      { "attachments" : [  ],
        "author" : { "description" : "",
            "first_name" : "",
            "id" : 1,
            "last_name" : "",
            "name" : "Napaba",
            "nickname" : "Napaba",
            "slug" : "napaba",
            "url" : ""
          },
        "categories" : [ { "description" : "",
              "id" : 6,
              "parent" : 4,
              "post_count" : 23,
              "slug" : "november-17th",
              "title" : "November 17th"
            },
            { "description" : "",
              "id" : 4,
              "parent" : 0,
              "post_count" : 114,
              "slug" : "program-schedule",
              "title" : "Program Schedule"
            }
          ],
        "comment_count" : 0,
        "comment_status" : "open",
        "comments" : [  ],
        "content" : "",
        "custom_fields" : { "event_time" : [ "7:00PM-9:00PM" ] },
        "date" : "2011-08-23 19:01:47",
        "excerpt" : "",
        "id" : 184,
        "modified" : "2011-08-23 19:01:47",
        "slug" : "napalsa-social-event%e2%80%a8stats-sports-bar-food-drink-provided",
        "status" : "publish",
        "tags" : [  ],
        "title" : "NAPALSA Social Event Stats Sports Bar (food & drink provided)",
        "title_plain" : "NAPALSA Social Event Stats Sports Bar (food & drink provided)",
        "type" : "post",
        "url" : "http://convention.napaba.org/2011/08/napalsa-social-event%e2%80%a8stats-sports-bar-food-drink-provided/"
      },
      { "attachments" : [  ],
        "author" : { "description" : "",
            "first_name" : "",
            "id" : 1,
            "last_name" : "",
            "name" : "Napaba",
            "nickname" : "Napaba",
            "slug" : "napaba",
            "url" : ""
          },
        "categories" : [ { "description" : "",
              "id" : 6,
              "parent" : 4,
              "post_count" : 23,
              "slug" : "november-17th",
              "title" : "November 17th"
            },
            { "description" : "",
              "id" : 4,
              "parent" : 0,
              "post_count" : 114,
              "slug" : "program-schedule",
              "title" : "Program Schedule"
            }
          ],
        "comment_count" : 0,
        "comment_status" : "open",
        "comments" : [  ],
        "content" : "",
        "custom_fields" : { "event_time" : [ "6:00PM-7:30PM" ] },
        "date" : "2011-08-23 19:01:22",
        "excerpt" : "",
        "id" : 182,
        "modified" : "2011-08-23 19:01:22",
        "slug" : "welcome-reception",
        "status" : "publish",
        "tags" : [  ],
        "title" : "Welcome Reception",
        "title_plain" : "Welcome Reception",
        "type" : "post",
        "url" : "http://convention.napaba.org/2011/08/welcome-reception/"
      },
      { "attachments" : [  ],
        "author" : { "description" : "",
            "first_name" : "",
            "id" : 1,
            "last_name" : "",
            "name" : "Napaba",
            "nickname" : "Napaba",
            "slug" : "napaba",
            "url" : ""
          },
        "categories" : [ { "description" : "",
              "id" : 6,
              "parent" : 4,
              "post_count" : 23,
              "slug" : "november-17th",
              "title" : "November 17th"
            },
            { "description" : "",
              "id" : 4,
              "parent" : 0,
              "post_count" : 114,
              "slug" : "program-schedule",
              "title" : "Program Schedule"
            }
          ],
        "comment_count" : 0,
        "comment_status" : "open",
        "comments" : [  ],
        "content" : "",
        "custom_fields" : { "event_time" : [ "5:00PM-6:30PM" ] },
        "date" : "2011-08-23 19:01:05",
        "excerpt" : "",
        "id" : 180,
        "modified" : "2011-08-23 19:01:05",
        "slug" : "napalsa-board-of-directors-meeting",
        "status" : "publish",
        "tags" : [  ],
        "title" : "NAPALSA Board of Directors Meeting",
        "title_plain" : "NAPALSA Board of Directors Meeting",
        "type" : "post",
        "url" : "http://convention.napaba.org/2011/08/napalsa-board-of-directors-meeting/"
      },
      { "attachments" : [  ],
        "author" : { "description" : "",
            "first_name" : "",
            "id" : 1,
            "last_name" : "",
            "name" : "Napaba",
            "nickname" : "Napaba",
            "slug" : "napaba",
            "url" : ""
          },
        "categories" : [ { "description" : "",
              "id" : 6,
              "parent" : 4,
              "post_count" : 23,
              "slug" : "november-17th",
              "title" : "November 17th"
            },
            { "description" : "",
              "id" : 4,
              "parent" : 0,
              "post_count" : 114,
              "slug" : "program-schedule",
              "title" : "Program Schedule"
            }
          ],
        "comment_count" : 0,
        "comment_status" : "open",
        "comments" : [  ],
        "content" : "",
        "custom_fields" : { "event_time" : [ "5:00PM-6:00PM" ] },
        "date" : "2011-08-23 19:00:32",
        "excerpt" : "",
        "id" : 178,
        "modified" : "2011-08-23 19:00:32",
        "slug" : "best-under-40-reception",
        "status" : "publish",
        "tags" : [  ],
        "title" : "Best Under 40 Reception",
        "title_plain" : "Best Under 40 Reception",
        "type" : "post",
        "url" : "http://convention.napaba.org/2011/08/best-under-40-reception/"
      },
      { "attachments" : [  ],
        "author" : { "description" : "",
            "first_name" : "",
            "id" : 1,
            "last_name" : "",
            "name" : "Napaba",
            "nickname" : "Napaba",
            "slug" : "napaba",
            "url" : ""
          },
        "categories" : [ { "description" : "",
              "id" : 6,
              "parent" : 4,
              "post_count" : 23,
              "slug" : "november-17th",
              "title" : "November 17th"
            },
            { "description" : "",
              "id" : 4,
              "parent" : 0,
              "post_count" : 114,
              "slug" : "program-schedule",
              "title" : "Program Schedule"
            }
          ],
        "comment_count" : 0,
        "comment_status" : "open",
        "comments" : [  ],
        "content" : "",
        "custom_fields" : { "event_time" : [ "3:30PM-5:00PM" ] },
        "date" : "2011-08-23 19:00:12",
        "excerpt" : "",
        "id" : 176,
        "modified" : "2011-08-23 19:00:12",
        "slug" : "public-interest-summit-reception",
        "status" : "publish",
        "tags" : [  ],
        "title" : "Public Interest Summit Reception",
        "title_plain" : "Public Interest Summit Reception",
        "type" : "post",
        "url" : "http://convention.napaba.org/2011/08/public-interest-summit-reception/"
      }
    ],
  "status" : "ok"
}