{ "category" : { "description" : "",
    "id" : 7,
    "parent" : 4,
    "post_count" : 56,
    "slug" : "november-18th",
    "title" : "November 18th"
},
    "count" : 50,
    "pages" : 2,
    "posts" : [ { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "10:00PM-2:00AM" ] },
               "date" : "2011-08-23 22:54:22",
               "excerpt" : "",
               "id" : 308,
               "modified" : "2011-08-23 22:54:22",
               "slug" : "late-night-lounge-series-2",
               "status" : "publish",
               "tags" : [  ],
               "title" : "Late Night Lounge Series",
               "title_plain" : "Late Night Lounge Series",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/late-night-lounge-series-2/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "8:30PM-12:00AM" ] },
               "date" : "2011-08-23 22:54:03",
               "excerpt" : "",
               "id" : 306,
               "modified" : "2011-11-04 20:07:38",
               "slug" : "poker-tournament",
               "status" : "publish",
               "tags" : [  ],
               "title" : "Poker Tournament  (limited to the first 40 paid event registrants)",
               "title_plain" : "Poker Tournament  (limited to the first 40 paid event registrants)",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/poker-tournament/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "8:30PM-12:00AM" ] },
               "date" : "2011-08-23 22:53:47",
               "excerpt" : "",
               "id" : 304,
               "modified" : "2011-11-04 18:47:19",
               "slug" : "game-nightkaraoke",
               "status" : "publish",
               "tags" : [  ],
               "title" : "Game Night/Karaoke",
               "title_plain" : "Game Night/Karaoke",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/game-nightkaraoke/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "8:00PM-10:00PM" ] },
               "date" : "2011-08-23 22:48:31",
               "excerpt" : "",
               "id" : 302,
               "modified" : "2011-08-23 22:48:31",
               "slug" : "napaba-partnersin-house-counsel-dinner",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA Partners/In-House Counsel Dinner",
               "title_plain" : "NAPABA Partners/In-House Counsel Dinner",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-partnersin-house-counsel-dinner/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "8:00PM-10:00PM" ] },
               "date" : "2011-08-23 22:48:26",
               "excerpt" : "",
               "id" : 865,
               "modified" : "2011-11-04 18:35:46",
               "slug" : "judicial-council-dinner-limited-to-bench-officers",
               "status" : "publish",
               "tags" : [  ],
               "title" : "Judicial Council Dinner (limited to Bench Officers)",
               "title_plain" : "Judicial Council Dinner (limited to Bench Officers)",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/judicial-council-dinner-limited-to-bench-officers/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "6:30PM-9:30PM" ] },
               "date" : "2011-08-23 22:48:13",
               "excerpt" : "",
               "id" : 300,
               "modified" : "2011-08-23 22:48:13",
               "slug" : "napalsa-dinner",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPALSA Dinner",
               "title_plain" : "NAPALSA Dinner",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napalsa-dinner/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "6:00PM-7:30PM" ] },
               "date" : "2011-08-23 22:47:54",
               "excerpt" : "",
               "id" : 298,
               "modified" : "2011-11-04 18:32:02",
               "slug" : "trailblazers-reception",
               "status" : "publish",
               "tags" : [  ],
               "title" : "Trailblazers Reception (sponsored by Walmart)",
               "title_plain" : "Trailblazers Reception (sponsored by Walmart)",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/trailblazers-reception/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "5:00PM-6:00PM" ] },
               "date" : "2011-08-23 22:47:36",
               "excerpt" : "",
               "id" : 296,
               "modified" : "2011-11-04 18:31:29",
               "slug" : "3rd-annual-napaba-lgbt-reception",
               "status" : "publish",
               "tags" : [  ],
               "title" : "3rd Annual NAPABA LGBT Reception, Speaker: Associate Justice Sabrina McKenna, Supreme Court of Hawaii (sponsored by King & Spanding, Lexis Nexis, and the National LGBT Bar Association)",
               "title_plain" : "3rd Annual NAPABA LGBT Reception, Speaker: Associate Justice Sabrina McKenna, Supreme Court of Hawaii (sponsored by King & Spanding, Lexis Nexis, and the National LGBT Bar Association)",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/3rd-annual-napaba-lgbt-reception/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "5:00PM-6:00PM" ] },
               "date" : "2011-08-23 22:47:31",
               "excerpt" : "",
               "id" : 851,
               "modified" : "2011-11-04 18:23:29",
               "slug" : "in-house-committee-reception-co-sponsored-by-alston-bird-llp-prudential",
               "status" : "publish",
               "tags" : [  ],
               "title" : "In-House Committee Reception (co-sponsored by Alston & Bird LLP & Prudential)",
               "title_plain" : "In-House Committee Reception (co-sponsored by Alston & Bird LLP & Prudential)",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/in-house-committee-reception-co-sponsored-by-alston-bird-llp-prudential/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "5:00PM-6:00PM" ] },
               "date" : "2011-08-23 22:47:26",
               "excerpt" : "",
               "id" : 855,
               "modified" : "2011-11-04 18:25:45",
               "slug" : "labor-employment-committee-reception",
               "status" : "publish",
               "tags" : [  ],
               "title" : "Labor & Employment Committee Reception",
               "title_plain" : "Labor & Employment Committee Reception",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/labor-employment-committee-reception/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "5:00PM-6:00PM" ] },
               "date" : "2011-08-23 22:47:17",
               "excerpt" : "",
               "id" : 294,
               "modified" : "2011-08-23 22:47:17",
               "slug" : "harvard-law-school-apa-alumni-reception",
               "status" : "publish",
               "tags" : [  ],
               "title" : "Harvard Law School APA Alumni reception",
               "title_plain" : "Harvard Law School APA Alumni reception",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/harvard-law-school-apa-alumni-reception/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "5:00PM-6:00PM" ] },
               "date" : "2011-08-23 22:47:15",
               "excerpt" : "",
               "id" : 846,
               "modified" : "2011-11-04 16:45:47",
               "slug" : "judiciary-committee-roundtable-by-invitation-only",
               "status" : "publish",
               "tags" : [  ],
               "title" : "Judiciary Committee Roundtable (by invitation only)",
               "title_plain" : "Judiciary Committee Roundtable (by invitation only)",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/judiciary-committee-roundtable-by-invitation-only/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "3:30PM-5:15PM" ] },
               "date" : "2011-08-23 22:46:49",
               "excerpt" : "",
               "id" : 292,
               "modified" : "2011-08-23 22:46:49",
               "slug" : "napalsa-general-meetings-elections",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPALSA General Meetings & Elections",
               "title_plain" : "NAPALSA General Meetings & Elections",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napalsa-general-meetings-elections/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "3:30PM-4:45PM" ] },
               "date" : "2011-08-23 22:46:13",
               "excerpt" : "",
               "id" : 288,
               "modified" : "2011-11-03 00:17:34",
               "slug" : "napaba-cle-breakout-sessions-iv-406-increasing-apa-presence-on-the-bench-the-do%e2%80%99s-don%e2%80%99ts-of-getting-more-apa-judges-elected-or-appointed-to-state-appellate-trial-courts-administ",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions IV- 406: Increasing APA Presence on the Bench: The Do’s & Don’ts of Getting More APA Judges Elected or Appointed to State Appellate, Trial Courts & Administrative Agencies",
               "title_plain" : "NAPABA CLE Breakout Sessions IV- 406: Increasing APA Presence on the Bench: The Do’s & Don’ts of Getting More APA Judges Elected or Appointed to State Appellate, Trial Courts & Administrative Agencies",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iv-406-increasing-apa-presence-on-the-bench-the-do%e2%80%99s-don%e2%80%99ts-of-getting-more-apa-judges-elected-or-appointed-to-state-appellate-trial-courts-administ/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "3:30PM-4:45PM" ] },
               "date" : "2011-08-23 22:45:52",
               "excerpt" : "",
               "id" : 286,
               "modified" : "2011-11-03 00:18:27",
               "slug" : "napaba-cle-breakout-sessions-iv-405-red-envelopes-of-cash-fcpa-anti-corruption-practice-enforcement-in-asia-the-need-for-sustainable-compliance-programs",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions IV- 405: Red Envelopes of Cash: FCPA & Anti-Corruption Practice Enforcement in Asia & the Need for Sustainable Compliance Programs",
               "title_plain" : "NAPABA CLE Breakout Sessions IV- 405: Red Envelopes of Cash: FCPA & Anti-Corruption Practice Enforcement in Asia & the Need for Sustainable Compliance Programs",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iv-405-red-envelopes-of-cash-fcpa-anti-corruption-practice-enforcement-in-asia-the-need-for-sustainable-compliance-programs/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "3:30PM-4:45PM" ] },
               "date" : "2011-08-23 22:44:56",
               "excerpt" : "",
               "id" : 282,
               "modified" : "2011-11-03 00:18:58",
               "slug" : "napaba-cle-breakout-sessions-iv-404-general-counsel-survival-skills",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions IV- 404: General Counsel Survival Skills",
               "title_plain" : "NAPABA CLE Breakout Sessions IV- 404: General Counsel Survival Skills",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iv-404-general-counsel-survival-skills/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "3:30PM-4:45PM" ] },
               "date" : "2011-08-23 22:44:31",
               "excerpt" : "",
               "id" : 280,
               "modified" : "2011-11-03 00:20:12",
               "slug" : "napaba-cle-breakout-sessions-iv-403-primer-on-renewable-energy-transactions",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions IV- 403: Primer on Renewable Energy Transactions",
               "title_plain" : "NAPABA CLE Breakout Sessions IV- 403: Primer on Renewable Energy Transactions",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iv-403-primer-on-renewable-energy-transactions/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "3:30PM-4:45PM" ] },
               "date" : "2011-08-23 22:34:16",
               "excerpt" : "",
               "id" : 278,
               "modified" : "2011-11-03 00:20:38",
               "slug" : "napaba-cle-breakout-sessions-iv-402-high-profile-and-complex-litigation-from-the-outside-in-tips-from-diverse-litigators-turned-in-house-counsel",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions IV- 402: High Profile and Complex Litigation from the Outside In: Tips from Diverse Litigators Turned In-house Counsel",
               "title_plain" : "NAPABA CLE Breakout Sessions IV- 402: High Profile and Complex Litigation from the Outside In: Tips from Diverse Litigators Turned In-house Counsel",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iv-402-high-profile-and-complex-litigation-from-the-outside-in-tips-from-diverse-litigators-turned-in-house-counsel/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "3:30PM-4:45PM" ] },
               "date" : "2011-08-23 22:33:53",
               "excerpt" : "",
               "id" : 276,
               "modified" : "2011-11-03 00:21:12",
               "slug" : "napaba-cle-breakout-sessions-iv-401-immigration-in-the-se-and-the-new-era-of-civil-rights",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions IV- 401: Immigration in the SE and the New Era of Civil Rights",
               "title_plain" : "NAPABA CLE Breakout Sessions IV- 401: Immigration in the SE and the New Era of Civil Rights",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iv-401-immigration-in-the-se-and-the-new-era-of-civil-rights/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "3:30PM-4:45PM" ] },
               "date" : "2011-08-23 22:33:29",
               "excerpt" : "",
               "id" : 274,
               "modified" : "2011-08-23 22:33:29",
               "slug" : "napaba-cle-breakout-sessions-iv",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions IV",
               "title_plain" : "NAPABA CLE Breakout Sessions IV",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iv/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "2:00PM-5:00PM" ] },
               "date" : "2011-08-23 22:28:19",
               "excerpt" : "",
               "id" : 272,
               "modified" : "2011-08-23 22:28:19",
               "slug" : "ihc-executive-coaching",
               "status" : "publish",
               "tags" : [  ],
               "title" : "IHC Executive Coaching",
               "title_plain" : "IHC Executive Coaching",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/ihc-executive-coaching/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "2:00PM-3:15PM" ] },
               "date" : "2011-08-23 22:27:42",
               "excerpt" : "",
               "id" : 270,
               "modified" : "2011-11-03 21:31:14",
               "slug" : "napaba-cle-breakout-sessions-iii-napalsa-breakout-session-5-ip-panel",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPALSA Breakout Session 5: The ABC’s of IP: Trends & Careers in Intellectual Property Law",
               "title_plain" : "NAPALSA Breakout Session 5: The ABC’s of IP: Trends & Careers in Intellectual Property Law",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iii-napalsa-breakout-session-5-ip-panel/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "2:00PM-3:15PM" ] },
               "date" : "2011-08-23 22:25:04",
               "excerpt" : "",
               "id" : 268,
               "modified" : "2011-11-03 21:29:47",
               "slug" : "napaba-cle-breakout-sessions-iii-napalsa-breakout-session-4-international-law-panel",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPALSA Breakout Session 4: Crossing Borders: International Practice Panel",
               "title_plain" : "NAPALSA Breakout Session 4: Crossing Borders: International Practice Panel",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iii-napalsa-breakout-session-4-international-law-panel/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "2:00PM-3:15PM" ] },
               "date" : "2011-08-23 22:23:24",
               "excerpt" : "",
               "id" : 266,
               "modified" : "2011-11-03 00:21:44",
               "slug" : "napaba-cle-breakout-sessions-iii-307-race-color-and-citizenship-ozawa-and-thind",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions III- 307: Race, Color and Citizenship: Ozawa and Thind",
               "title_plain" : "NAPABA CLE Breakout Sessions III- 307: Race, Color and Citizenship: Ozawa and Thind",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iii-307-race-color-and-citizenship-ozawa-and-thind/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "2:00PM-3:15PM" ] },
               "date" : "2011-08-23 22:22:59",
               "excerpt" : "",
               "id" : 264,
               "modified" : "2011-11-03 00:22:17",
               "slug" : "napaba-cle-breakout-sessions-iii-306-securing-local-compliance-with-section-203-of-voting-rights-act",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions III- 306: Securing Local Compliance with Section 203 of Voting Rights Act",
               "title_plain" : "NAPABA CLE Breakout Sessions III- 306: Securing Local Compliance with Section 203 of Voting Rights Act",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iii-306-securing-local-compliance-with-section-203-of-voting-rights-act/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "2:00PM-3:15PM" ] },
               "date" : "2011-08-23 22:21:36",
               "excerpt" : "",
               "id" : 262,
               "modified" : "2011-11-03 00:22:45",
               "slug" : "napaba-cle-breakout-sessions-iii-305-lawyers-on-the-move-how-to-sustain-your-career-by-spreading-your-wings",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions III- 305: Lawyers on the Move: How to Sustain Your Career by Spreading Your Wings",
               "title_plain" : "NAPABA CLE Breakout Sessions III- 305: Lawyers on the Move: How to Sustain Your Career by Spreading Your Wings",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iii-305-lawyers-on-the-move-how-to-sustain-your-career-by-spreading-your-wings/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "2:00PM-3:15PM" ] },
               "date" : "2011-08-23 22:18:16",
               "excerpt" : "",
               "id" : 260,
               "modified" : "2011-11-03 00:23:05",
               "slug" : "napaba-cle-breakout-sessions-iii-304-protecting-your-client%e2%80%99s-intangible-rights",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions III- 304: Protecting Your Client’s Intangible Rights",
               "title_plain" : "NAPABA CLE Breakout Sessions III- 304: Protecting Your Client’s Intangible Rights",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iii-304-protecting-your-client%e2%80%99s-intangible-rights/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "2:00PM-3:15PM" ] },
               "date" : "2011-08-23 22:17:54",
               "excerpt" : "",
               "id" : 258,
               "modified" : "2011-11-03 00:23:20",
               "slug" : "napaba-cle-breakout-sessions-iii-303-hot-topics-in-securities-law-beyond-dodd-frank",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions III- 303: Hot topics in Securities Law Beyond Dodd-Frank",
               "title_plain" : "NAPABA CLE Breakout Sessions III- 303: Hot topics in Securities Law Beyond Dodd-Frank",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iii-303-hot-topics-in-securities-law-beyond-dodd-frank/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "2:00PM-3:15PM" ] },
               "date" : "2011-08-23 22:17:33",
               "excerpt" : "",
               "id" : 256,
               "modified" : "2011-11-03 21:28:39",
               "slug" : "napaba-cle-breakout-sessions-iii-302-international-commercial-arbitration",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions III- 302: International Business Disputes: Insights from the Inside Players",
               "title_plain" : "NAPABA CLE Breakout Sessions III- 302: International Business Disputes: Insights from the Inside Players",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iii-302-international-commercial-arbitration/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "2:00PM-3:15PM" ] },
               "date" : "2011-08-23 22:15:10",
               "excerpt" : "",
               "id" : 254,
               "modified" : "2011-11-03 00:23:50",
               "slug" : "napaba-cle-breakout-sessions-iii-301-does-tiger-mothering-produce-paper-tigers",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions III- 301: Realities of Life in the Jungle for the Tiger Cub",
               "title_plain" : "NAPABA CLE Breakout Sessions III- 301: Realities of Life in the Jungle for the Tiger Cub",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iii-301-does-tiger-mothering-produce-paper-tigers/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "2:00PM-3:15PM" ] },
               "date" : "2011-08-23 22:10:19",
               "excerpt" : "",
               "id" : 250,
               "modified" : "2011-08-23 22:13:37",
               "slug" : "napaba-cle-breakout-sessions-iii",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions III",
               "title_plain" : "NAPABA CLE Breakout Sessions III",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-iii/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "1:30PM-3:00PM" ] },
               "date" : "2011-08-23 22:08:47",
               "excerpt" : "",
               "id" : 248,
               "modified" : "2011-08-23 22:08:47",
               "slug" : "thomas-tang-moot-court-competition-round-2",
               "status" : "publish",
               "tags" : [  ],
               "title" : "Thomas Tang Moot Court Competition-Round 2",
               "title_plain" : "Thomas Tang Moot Court Competition-Round 2",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/thomas-tang-moot-court-competition-round-2/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "12:30PM-1:45PM" ] },
               "date" : "2011-08-23 22:07:02",
               "excerpt" : "",
               "id" : 244,
               "modified" : "2011-11-03 00:31:43",
               "slug" : "luncheon-plenary-session",
               "status" : "publish",
               "tags" : [  ],
               "title" : "Luncheon & Plenary Session: Yale Law Professor & Bestselling Author Amy Chua (Co-Sponsored by Allstate & Schiff Hardin, LLP)",
               "title_plain" : "Luncheon & Plenary Session: Yale Law Professor & Bestselling Author Amy Chua (Co-Sponsored by Allstate & Schiff Hardin, LLP)",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/luncheon-plenary-session/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "11:00AM-12:15PM" ] },
               "date" : "2011-08-23 22:06:35",
               "excerpt" : "",
               "id" : 242,
               "modified" : "2011-11-03 21:16:45",
               "slug" : "napaba-cle-breakout-sessions-ii-napalsa-breakout-session-2-bankruptcy-panel",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPALSA Breakout Session 2: Opportunities in a Depressed Economy-Legal Careers in Bankruptcy & Restructuring",
               "title_plain" : "NAPALSA Breakout Session 2: Opportunities in a Depressed Economy-Legal Careers in Bankruptcy & Restructuring",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-ii-napalsa-breakout-session-2-bankruptcy-panel/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "11:00AM-12:15PM" ] },
               "date" : "2011-08-23 22:06:06",
               "excerpt" : "",
               "id" : 240,
               "modified" : "2011-11-03 21:13:58",
               "slug" : "napaba-cle-breakout-sessions-ii-napalsa-breakout-session-1-resume-interview-tips",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPALSA Breakout Session 1: Getting the Job: Interview/Resume Tips",
               "title_plain" : "NAPALSA Breakout Session 1: Getting the Job: Interview/Resume Tips",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-ii-napalsa-breakout-session-1-resume-interview-tips/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "11:00AM-12:15PM" ] },
               "date" : "2011-08-23 22:05:24",
               "excerpt" : "",
               "id" : 238,
               "modified" : "2011-11-03 00:24:10",
               "slug" : "napaba-cle-breakout-sessions-ii-207-gitmo-%e2%80%93-10-years-after-911",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions II- 207: Gitmo – 10 Years after 9/11",
               "title_plain" : "NAPABA CLE Breakout Sessions II- 207: Gitmo – 10 Years after 9/11",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-ii-207-gitmo-%e2%80%93-10-years-after-911/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "11:00AM-12:15PM" ] },
               "date" : "2011-08-23 22:03:18",
               "excerpt" : "",
               "id" : 236,
               "modified" : "2011-11-03 00:24:22",
               "slug" : "napaba-cle-breakout-sessions-ii-206-legal-strategies-for-sustaining-corporate-growth-through-successful-integration-post-ma-deals",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions II- 206: Legal Strategies for Sustaining Corporate Growth through Successful Integration Post M&A Deals",
               "title_plain" : "NAPABA CLE Breakout Sessions II- 206: Legal Strategies for Sustaining Corporate Growth through Successful Integration Post M&A Deals",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-ii-206-legal-strategies-for-sustaining-corporate-growth-through-successful-integration-post-ma-deals/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "11:00AM-12:15PM" ] },
               "date" : "2011-08-23 22:01:24",
               "excerpt" : "",
               "id" : 234,
               "modified" : "2011-11-03 00:24:34",
               "slug" : "napaba-cle-breakout-sessions-ii-205-global-ip-war-current-trends-strategies",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions II- 205: Global IP War: Current Trends & Strategies",
               "title_plain" : "NAPABA CLE Breakout Sessions II- 205: Global IP War: Current Trends & Strategies",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-ii-205-global-ip-war-current-trends-strategies/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "11:00AM-12:15PM" ] },
               "date" : "2011-08-23 21:55:53",
               "excerpt" : "",
               "id" : 228,
               "modified" : "2011-11-03 00:24:46",
               "slug" : "napaba-cle-breakout-sessions-ii-204-the-future-of-cleantech-perspectives-from-california-beyond",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions II- 204: The Future of Cleantech: Perspectives from California & Beyond",
               "title_plain" : "NAPABA CLE Breakout Sessions II- 204: The Future of Cleantech: Perspectives from California & Beyond",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-ii-204-the-future-of-cleantech-perspectives-from-california-beyond/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "11:00AM-12:15PM" ] },
               "date" : "2011-08-23 21:54:23",
               "excerpt" : "",
               "id" : 226,
               "modified" : "2011-11-03 00:24:59",
               "slug" : "napaba-cle-breakout-sessions-ii-203-sustaining-a-competitive-ip-practice-in-an-evolving-market-what-every-ip-lawyer-needs-to-know-about-recent-cases-trends",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions II- 203: Sustaining a Competitive IP Practice in an Evolving Market: What Every IP Lawyer Needs to Know about Recent Cases & Trends",
               "title_plain" : "NAPABA CLE Breakout Sessions II- 203: Sustaining a Competitive IP Practice in an Evolving Market: What Every IP Lawyer Needs to Know about Recent Cases & Trends",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-ii-203-sustaining-a-competitive-ip-practice-in-an-evolving-market-what-every-ip-lawyer-needs-to-know-about-recent-cases-trends/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "11:00AM-12:15PM" ] },
               "date" : "2011-08-23 21:53:20",
               "excerpt" : "",
               "id" : 224,
               "modified" : "2011-11-03 00:25:09",
               "slug" : "napaba-cle-breakout-sessions-ii-202-best-practices-at-corporations-to-promote-diversity",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions II- 202: Best Practices at Corporations to Promote Diversity",
               "title_plain" : "NAPABA CLE Breakout Sessions II- 202: Best Practices at Corporations to Promote Diversity",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-ii-202-best-practices-at-corporations-to-promote-diversity/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "11:00AM-12:15PM" ] },
               "date" : "2011-08-23 21:52:19",
               "excerpt" : "",
               "id" : 222,
               "modified" : "2011-11-03 00:25:20",
               "slug" : "napaba-cle-breakout-sessions-ii-201-international-economic-development-case-studies-of-asian-companies-in-the-u-s",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions II-201: International Economic Development: Case Studies of Asian Companies in the U.S.",
               "title_plain" : "NAPABA CLE Breakout Sessions II-201: International Economic Development: Case Studies of Asian Companies in the U.S.",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-ii-201-international-economic-development-case-studies-of-asian-companies-in-the-u-s/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "11:00AM-12:15PM" ] },
               "date" : "2011-08-23 21:52:18",
               "excerpt" : "",
               "id" : 220,
               "modified" : "2011-11-03 20:57:19",
               "slug" : "napaba-cle-breakout-sessions-ii",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions II",
               "title_plain" : "NAPABA CLE Breakout Sessions II",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-ii/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "10:00AM-11:30AM" ] },
               "date" : "2011-08-23 21:51:50",
               "excerpt" : "",
               "id" : 218,
               "modified" : "2011-11-03 21:03:07",
               "slug" : "thomas-tang-moot-court-competition-round-1",
               "status" : "publish",
               "tags" : [  ],
               "title" : "Thomas Tang Moot Court Competition-Round 1",
               "title_plain" : "Thomas Tang Moot Court Competition-Round 1",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/thomas-tang-moot-court-competition-round-1/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "9:30AM-5:00PM" ] },
               "date" : "2011-08-23 21:50:53",
               "excerpt" : "",
               "id" : 246,
               "modified" : "2011-11-03 21:02:41",
               "slug" : "3rd-annual-napaba-pitch-sessions-program",
               "status" : "publish",
               "tags" : [  ],
               "title" : "3RD ANNUAL NAPABA PITCH SESSIONS PROGRAM",
               "title_plain" : "3RD ANNUAL NAPABA PITCH SESSIONS PROGRAM",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/3rd-annual-napaba-pitch-sessions-program/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "9:30AM-10:45AM" ] },
               "date" : "2011-08-23 21:50:24",
               "excerpt" : "",
               "id" : 216,
               "modified" : "2011-11-03 20:15:45",
               "slug" : "napaba-cle-breakout-sessions-i-napalsa-welcome-session-plus-meet-greet",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPALSA Welcome Session (plus meet & greet)",
               "title_plain" : "NAPALSA Welcome Session (plus meet & greet)",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-i-napalsa-welcome-session-plus-meet-greet/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "9:30AM-10:45AM" ] },
               "date" : "2011-08-23 21:50:00",
               "excerpt" : "",
               "id" : 214,
               "modified" : "2011-11-03 00:25:37",
               "slug" : "napaba-cle-breakout-sessions-i-106-cloud-computing-with-a-chance-of-meatballs",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions I- 106: Cloud Computing with a Chance of Meatballs",
               "title_plain" : "NAPABA CLE Breakout Sessions I- 106: Cloud Computing with a Chance of Meatballs",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-i-106-cloud-computing-with-a-chance-of-meatballs/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "9:30AM-10:45AM" ] },
               "date" : "2011-08-23 21:49:08",
               "excerpt" : "",
               "id" : 212,
               "modified" : "2011-11-03 00:25:49",
               "slug" : "napaba-cle-breakout-sessions-i-105-hot-topics-in-labor-and-employment-law",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions I- 105: Hot Topics in Labor and Employment Law",
               "title_plain" : "NAPABA CLE Breakout Sessions I- 105: Hot Topics in Labor and Employment Law",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-i-105-hot-topics-in-labor-and-employment-law/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "9:30AM-10:45AM" ] },
               "date" : "2011-08-23 21:48:38",
               "excerpt" : "",
               "id" : 210,
               "modified" : "2011-11-03 00:26:48",
               "slug" : "napaba-cle-breakout-sessions-i-104-3rd-annual-master-class",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions I- 104: 3rd Annual Master Class: Best Practices Workshop ‐ Building Successful Business Development Skills with Social Media",
               "title_plain" : "NAPABA CLE Breakout Sessions I- 104: 3rd Annual Master Class: Best Practices Workshop ‐ Building Successful Business Development Skills with Social Media",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-i-104-3rd-annual-master-class/"
               },
               { "attachments" : [  ],
               "author" : { "description" : "",
               "first_name" : "",
               "id" : 1,
               "last_name" : "",
               "name" : "Napaba",
               "nickname" : "Napaba",
               "slug" : "napaba",
               "url" : ""
               },
               "categories" : [ { "description" : "",
                               "id" : 7,
                               "parent" : 4,
                               "post_count" : 56,
                               "slug" : "november-18th",
                               "title" : "November 18th"
                               },
                               { "description" : "",
                               "id" : 4,
                               "parent" : 0,
                               "post_count" : 121,
                               "slug" : "program-schedule",
                               "title" : "Program Schedule"
                               }
                               ],
               "comment_count" : 0,
               "comment_status" : "open",
               "comments" : [  ],
               "content" : "",
               "custom_fields" : { "event_time" : [ "9:30AM-10:45AM" ] },
               "date" : "2011-08-23 21:48:09",
               "excerpt" : "",
               "id" : 208,
               "modified" : "2011-11-03 00:27:09",
               "slug" : "napaba-cle-breakout-sessions-i-103-beyond-sustainability-advancing-apa-lawyers-in-law-firms",
               "status" : "publish",
               "tags" : [  ],
               "title" : "NAPABA CLE Breakout Sessions I- 103: Beyond Sustainability: Advancing APA Lawyers in Law Firms",
               "title_plain" : "NAPABA CLE Breakout Sessions I- 103: Beyond Sustainability: Advancing APA Lawyers in Law Firms",
               "type" : "post",
               "url" : "http://convention.napaba.org/2011/08/napaba-cle-breakout-sessions-i-103-beyond-sustainability-advancing-apa-lawyers-in-law-firms/"
               }
               ],
    "status" : "ok"
}